### ISSUE TITLE
Please release a build to VSIX Gallery - happy to help if needed

### ISSUE THREAD

**Issue by ErikEJ** [bricelam/VS.Data.Sqlite#2]
If available, would make life of SQLite and EF Core Power Tools users much better.

- [ ] Increase version numbers in manifest and assembly info
- [ ] Upload to VSIX Gallery on completed build 

(I use this PS script from Mads Kristensen with AppVeyor)

Before build:
```powershell
(new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion 
```

After completed build:
```powershell
Vsix-PushArtifacts | Vsix-PublishToGallery
```

**Comment by bricelam** [comment]
Hmm... Did it work? It [said it did](https://github.com/bricelam/VS.Data.Sqlite/runs/7352122128#step:8:1). We'll see if it shows up.

**Comment by bricelam** [comment]
Ah, it's not handling the wildcard. Let's see how [this one](https://github.com/bricelam/VS.Data.Sqlite/runs/7352349226) goes.

**Comment by bricelam** [comment]
![ITS ALIVE](https://user-images.githubusercontent.com/1226749/179155302-9f6a68f2-f4f9-47ce-a277-3571f15ecad2.gif)

**Comment by ErikEJ** [comment]
Wh hu! Just need a nice icon and some licensing!

**Comment by ErikEJ** [comment]
https://www.vsixgallery.com/extension/0b471821-68a4-49dd-b175-e6daf4e5cebf

**Comment by ErikEJ** [comment]
I have added support for this DDEX provider in the latest daily build of EF Core Power Tools!

**Comment by ErikEJ** [comment]
Updated the docs: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-data-source
