### ISSUE TITLE
Publish preview to VS Marketplace

### ISSUE THREAD

**Issue by ErikEJ** [bricelam/VS.Data.Sqlite#26]
Then I can make it a dependency in EF Core Power Tools!

```xml
    <Dependencies>
        <Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" d:Source="Manual" Version="[4.7.2,)" />
        <Dependency d:Source="Installed" Id="0b471821-68a4-49dd-b175-e6daf4e5cebf" DisplayName="VisualStudio.Data.Sqlite" Version="[0.0.9.62085,1.0)" />
    </Dependencies>

```

**Comment by bricelam** [comment]
😱 But... it's not done! lol, I *was* going to wait until I finished [the 1.0.0 issues](https://github.com/bricelam/VS.Data.Sqlite/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0), but maybe I can do it sooner if it's clearly marked as a preview.

**Comment by ErikEJ** [comment]
No Rush... but publishing early is a good opportunity for feedback.

**Comment by ErikEJ** [comment]
Preview experience https://devblogs.microsoft.com/visualstudio/new-preview-label-for-visual-studio-extensions-2/

**Comment by bricelam** [comment]
Done. https://marketplace.visualstudio.com/items?itemName=bricelam.VSDataSqlite

**Comment by ErikEJ** [comment]
Hmm. Do not see it? Is it public?
