### ISSUE TITLE
What is this project for?

### ISSUE THREAD

**Issue by bricelam** [bricelam/VS.Data.Sqlite#5]
I enjoy working on this project when I have the time, but before I release anything, I really need to decide what it's for--and what it's *not* for. With so many amazing tools like [SQLite Toolbox](https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox), [DB Browser for SQLite](https://sqlitebrowser.org/), [DataGrip](https://www.jetbrains.com/datagrip/), etc. why should this one exist?

### For

* Debugging .NET applications inside Visual Studio
  * Verifying the schema
  * Verifying the data
  * Working with in-memory databases
* Enabling other VS extensions that use DDEX providers
  * Creating connection strings
  * Creating design-time connections
  * Reading schemas

### Not for

* Creating databases
* Modifying databases
* Designing databases
* Designing queries
  * Reviewing query plans
* Comparing databases
* Importing/exporting data
* Migrating databases
* Generating code

### TBD

* Applications using System.Data.SQLite

**Comment by ErikEJ** [comment]
Maybe useful to move this to readme.md ?
